# Generated by Django 6.0.7 on 2026-07-11 01:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_unique_category_normalized_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('positive_adjustment', 'Ajuste positivo'), ('negative_adjustment', 'Ajuste negativo')], max_length=30)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField()),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'created_at'], name='inventory_s_product_5919a9_idx'), models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx')],
            },
        ),
    ]
